# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: This is Only a Test
email: jessica@versaw.com
description: > # this means to ignore newlines until "baseurl:"
  The trials and errors of a twenty something living in the heartland.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jessica.versaw.com" # the base hostname & protocol for your site
twitter_username: jraeversaw
github_username:  jessica-versaw

# Build settings
markdown: kramdown
