# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jessica Writes Things
email: jessica@versaw.com
description: > # this means to ignore newlines until "baseurl:"
  My assumption is at least three people are interested in what I have to say. Only two gave birth to me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jessica.versaw.com" # the base hostname & protocol for your site
twitter_username: jraeversaw
github_username:  jessica-versaw
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-81872870-1
